### ISSUE TITLE
twitter シェア リンク

### ISSUE THREAD

**Issue by in-the-box** [pixelgram/iwasborn_shake_music#8]
http://twitter.com/share?url=[シェアするURL]&text=[ツイート内テキスト]&via=[ツイート内に含むユーザ名]&related=[ツイート後に表示されるユーザー]&hashtags=[ハッシュタグ]

**Comment by n-a-t** [comment]
http://twitter.com/share?url=[https://huttezuborn.netlify.com/]&text=愛はズボーン 新音源「でもごるごん」先行試聴特別コンテンツ。振って聴ける新しい感覚を体験！&via=iwasborn_band&related=iwasborn_band&hashtags=振ってズボーン,でもごるごん,愛はズボーン
